### ISSUE TITLE
如何制作自定义字库？

### ISSUE THREAD

**Issue by liuxd** [janx/ruby-pinyin#17]
@janx 

文档中有提到使用自定义字库的用法：

```
PinYin.override_files = [File.expand_path('../my.dat', __FILE__)]
```

但是，`my.dat`文件的制作约定有哪些？使用什么编码？什么格式？麻烦在文档中说明一下。

**Comment by zhulinpinyu** [comment]
+1

**Comment by janx** [comment]
已更新Readme: https://github.com/janx/ruby-pinyin#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%91%E9%9F%B3
