### ISSUE TITLE
PinYin.of_string('×甲乙') => ["jia", "jia"]

### ISSUE THREAD

**Issue by ShikChen** [janx/ruby-pinyin#18]
``` ruby
require 'ruby-pinyin'
p PinYin.of_string('×甲乙')
```

The correct result should be `["jia", "yi"]`, but it shows `["jia", "jia"]`.

**Comment by janx** [comment]
Thanks @forresty for providing a quick fix.

Because 'x' is an actual character, simply discard it in result may not be the best choice. I'll figure out if there's better solution in v1.0.
