### ISSUE TITLE
八大山人 -> ba tai shan ren

### ISSUE THREAD

**Issue by Prajna** [janx/ruby-pinyin#20]
irb(main):001:0> PinYin.of_string '大'
=> ["da"]
irb(main):002:0> PinYin.of_string '八大'
=> ["ba", "da"]
irb(main):003:0> PinYin.of_string '八大山人'
=> ["ba", "tai", "shan", "ren"]
irb(main):004:0> PinYin.of_string '大山'
=> ["tai", "shan"]

这是怎么回事呢？

**Comment by janx** [comment]
`大山`的拼音数据有误，更新到最新版本可解决。:beers:

**Comment by Prajna** [comment]
好的，谢谢 :beer:
