### ISSUE TITLE
rmmseg.so (LoadError)

### ISSUE THREAD

**Issue by faradaytrs** [janx/ruby-pinyin#24]
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/lib/rmmseg.rb:2:in `require': 126: �� ������ ��������� ������.   - C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/rmmseg.so (LoadError)
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/lib/rmmseg.rb:2:in `<top (required)>'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruby-pinyin-0.4.8/lib/ruby-pinyin/backend/mmseg.rb:3:in `require'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruby-pinyin-0.4.8/lib/ruby-pinyin/backend/mmseg.rb:3:in `<top (required)>'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruby-pinyin-0.4.8/lib/ruby-pinyin.rb:41:in `<top (required)>'

rmmseg-cpp 0.2.9
ruby 2.2.3
gem 2.4.5.1

What to do?

**Comment by faradaytrs** [comment]
gem install rmmseg-cpp --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rmmseg-cpp
200 OK
Temporarily enhancing PATH to include DevKit...
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/History.txt
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/Manifest.txt
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/README
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/Rakefile
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/bin/rmmseg
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/data/chars.dic
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/data/words.dic
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/algor.cpp
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/algor.h
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/chunk.h
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/dict.cpp
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/dict.h
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/extconf.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/memory.cpp
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/memory.h
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/rmmseg.cpp
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/rules.h
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/token.h
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/ext/rmmseg/word.h
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/lib/rmmseg.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/lib/rmmseg/dictionary.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/lib/rmmseg/ferret.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/misc/convert.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/misc/ferret_example.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/misc/homepage.erb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/misc/homepage.html
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/spec/rmmseg_spec.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/spec/spec_helper.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/ann.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/bones.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/gem.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/git.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/homepage.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/manifest.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/notes.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/post_load.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/rdoc.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/rubyforge.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/setup.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/spec.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/svn.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/tasks/test.rake
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rmmseg-cpp-0.2.9/test/test_rmmseg.rb
Building native extensions.  This could take a while...
C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20160106-9964-v7ii96.rb extconf.rb
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
generating rmmseg-x64-mingw32.def
compiling algor.cpp
compiling dict.cpp
compiling memory.cpp
compiling rmmseg.cpp
linking shared-object rmmseg.so
make "DESTDIR=" install
/usr/bin/install -c -m 0755 rmmseg.so ./.gem.20160106-9964-w97896

C:/Ruby22-x64/bin/rmmseg
C:/Ruby22-x64/bin/rmmseg.bat
Successfully installed rmmseg-cpp-0.2.9
Parsing documentation for rmmseg-cpp-0.2.9
Parsing sources...
100% [26/26]  lib/rmmseg/ferret.rb
Done installing documentation for rmmseg-cpp after 0 seconds
1 gem installed

**Comment by Eric-Guo** [comment]
@janx 合并[PR26](https://github.com/janx/ruby-pinyin/pull/26)即可修正这个问题。

**Comment by janx** [comment]
fixed by #26
